import numpy as np
x=([2,3,1],[2,1,4],[1,7,6])
y=([1,8,4],[8,9,6],[2,9,5])
z=([5,6,7],[6,9,3],[7,6,3])
a=np.multiply(x,x)
print("a is ", a)
b=np.add(y,y)
print("b is" , b)
c=np.multiply(z,z)
print("c is " , c)
d=np.multiply(c,z)
print("d is " , d)
e=np.add(a,b)
print("e is " , e)
f=np.subtract(e,d)
print("result is " , f)
